require("src.object.base_object")
require("src.object.trigger")

require("src.object.box")
require("src.object.gate")
require("src.object.graphic")
require("src.object.hard_switch")
require("src.object.lantern")
require("src.object.lever")
require("src.object.switch")
