SCREEN_WIDTH = 320
SCREEN_HEIGHT = 180
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
TILE_SIZE = 10
TILES_X = math.floor(SCREEN_WIDTH / TILE_SIZE)
TILES_Y = math.floor(SCREEN_HEIGHT / TILE_SIZE)
UI_Z_INDEX = 100
